# Generated by Django 3.1.7 on 2021-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=60)),
                ('artist_id', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=60, unique=True)),
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('is_old_user', models.BooleanField(default=False)),
                ('recommendation_frame', models.IntegerField(default=0)),
            ],
        ),
    ]
