# Generated by Django 3.1.1 on 2021-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('rating_estandar', models.FloatField()),
                ('artist_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('artist_id', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=60)),
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
