# Generated by Django 3.1.7 on 2021-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interactions',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
