# Generated by Django 3.1.7 on 2021-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210307_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
