# Generated by Django 3.1.7 on 2021-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210307_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistLiked',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=60)),
                ('artist_id', models.CharField(max_length=255)),
            ],
        ),
    ]
